In [1]:
import pandas as pd
df = pd.read_csv("ocorrencia.csv",nrows=2000, sep=";", parse_dates=['ocorrencia_dia'], dayfirst=True)
df.head()

,codigo_ocorrencia,codigo_ocorrencia1,codigo_ocorrencia2,codigo_ocorrencia3,codigo_ocorrencia4,ocorrencia_classificacao,ocorrencia_latitude,ocorrencia_longitude,ocorrencia_cidade,ocorrencia_uf,...,ocorrencia_dia,ocorrencia_hora,investigacao_aeronave_liberada,investigacao_status,divulgacao_relatorio_numero,divulgacao_relatorio_publicado,divulgacao_dia_publicacao,total_recomendacoes,total_aeronaves_envolvidas,ocorrencia_saida_pista
0,40211,40211,40211,40211,40211,INCIDENTE,***,***,RIO DE JANEIRO,RJ,...,2010-01-03,12:00:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO
1,40349,40349,40349,40349,40349,INCIDENTE,NaN,NaN,BELÉM,PA,...,2010-01-03,11:05:00,SIM,FINALIZADA,NaN,NÃO,NaN,0,1,NÃO
2,40351,40351,40351,40351,40351,INCIDENTE,NaN,NaN,RIO DE JANEIRO,RJ,...,2010-01-03,03:00:00,SIM,FINALIZADA,NaN,NÃO,NaN,0,1,NÃO
3,39527,39527,39527,39527,39527,ACIDENTE,-13.1066666667,-55.9930555556,LUCAS DO RIO VERDE,MT,...,2010-01-04,17:30:00,SIM,FINALIZADA,A-539/CENIPA/2018,SIM,2019-10-28,0,1,NÃO
4,40324,40324,40324,40324,40324,INCIDENTE,NaN,NaN,PELOTAS,RS,...,2010-01-05,19:25:00,SIM,FINALIZADA,NaN,NÃO,NaN,0,1,NÃO

In [2]:
#dataframe = matriz de dados = usa função loc
#função loc = linha, coluna

df.loc[1, 'ocorrencia_cidade']

'BELÉM'

In [8]:
# df.loc[1] = linha
# df.loc[1:3] = linha x até tal
# df.loc[[10,40]] = lista duas linhas
# df.loc[:,'ocorrencia_cidade'] =todos dados da coluna

0           RIO DE JANEIRO
1                    BELÉM
2           RIO DE JANEIRO
3       LUCAS DO RIO VERDE
4                  PELOTAS
               ...
1995               CAJAMAR
1996      ATALAIA DO NORTE
1997                 BELÉM
1998            ITAPIRAPUÃ
1999               VILHENA
Name: ocorrencia_cidade, Length: 2000, dtype: object

In [11]:

df.codigo_ocorrencia.is_unique  #verificar se contem itens unicos

True

In [14]:
df.set_index('codigo_ocorrencia', inplace=True) #alterar o label indice

In [15]:
df.head()

,codigo_ocorrencia1,codigo_ocorrencia2,codigo_ocorrencia3,codigo_ocorrencia4,ocorrencia_classificacao,ocorrencia_latitude,ocorrencia_longitude,ocorrencia_cidade,ocorrencia_uf,ocorrencia_pais,...,ocorrencia_dia,ocorrencia_hora,investigacao_aeronave_liberada,investigacao_status,divulgacao_relatorio_numero,divulgacao_relatorio_publicado,divulgacao_dia_publicacao,total_recomendacoes,total_aeronaves_envolvidas,ocorrencia_saida_pista
codigo_ocorrencia,,,,,,,,,,,,,,,,,,,,,
40211,40211,40211,40211,40211,INCIDENTE,***,***,RIO DE JANEIRO,RJ,BRASIL,...,2010-01-03,12:00:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO
40349,40349,40349,40349,40349,INCIDENTE,NaN,NaN,BELÉM,PA,BRASIL,...,2010-01-03,11:05:00,SIM,FINALIZADA,NaN,NÃO,NaN,0,1,NÃO
40351,40351,40351,40351,40351,INCIDENTE,NaN,NaN,RIO DE JANEIRO,RJ,BRASIL,...,2010-01-03,03:00:00,SIM,FINALIZADA,NaN,NÃO,NaN,0,1,NÃO
39527,39527,39527,39527,39527,ACIDENTE,-13.1066666667,-55.9930555556,LUCAS DO RIO VERDE,MT,BRASIL,...,2010-01-04,17:30:00,SIM,FINALIZADA,A-539/CENIPA/2018,SIM,2019-10-28,0,1,NÃO
40324,40324,40324,40324,40324,INCIDENTE,NaN,NaN,PELOTAS,RS,BRASIL,...,2010-01-05,19:25:00,SIM,FINALIZADA,NaN,NÃO,NaN,0,1,NÃO

In [16]:
df.loc[40324]

codigo_ocorrencia1                              40324
codigo_ocorrencia2                              40324
codigo_ocorrencia3                              40324
codigo_ocorrencia4                              40324
ocorrencia_classificacao                    INCIDENTE
ocorrencia_latitude                               NaN
ocorrencia_longitude                              NaN
ocorrencia_cidade                             PELOTAS
ocorrencia_uf                                      RS
ocorrencia_pais                                BRASIL
ocorrencia_aerodromo                             SBPK
ocorrencia_dia                    2010-01-05 00:00:00
ocorrencia_hora                              19:25:00
investigacao_aeronave_liberada                    SIM
investigacao_status                        FINALIZADA
divulgacao_relatorio_numero                       NaN
divulgacao_relatorio_publicado                    NÃO
divulgacao_dia_publicacao                         NaN
total_recomendacoes                                 0
total_aeronaves_envolvidas                          1
ocorrencia_saida_pista                            NÃO
Name: 40324, dtype: object

In [17]:
df.reset_index(drop=True, inplace=True) #revertendo o index como de inicio

In [19]:
df.head()

,codigo_ocorrencia1,codigo_ocorrencia2,codigo_ocorrencia3,codigo_ocorrencia4,ocorrencia_classificacao,ocorrencia_latitude,ocorrencia_longitude,ocorrencia_cidade,ocorrencia_uf,ocorrencia_pais,...,ocorrencia_dia,ocorrencia_hora,investigacao_aeronave_liberada,investigacao_status,divulgacao_relatorio_numero,divulgacao_relatorio_publicado,divulgacao_dia_publicacao,total_recomendacoes,total_aeronaves_envolvidas,ocorrencia_saida_pista
0,40211,40211,40211,40211,INCIDENTE,***,***,RIO DE JANEIRO,RJ,BRASIL,...,2010-01-03,12:00:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO
1,40349,40349,40349,40349,INCIDENTE,NaN,NaN,BELÉM,PA,BRASIL,...,2010-01-03,11:05:00,SIM,FINALIZADA,NaN,NÃO,NaN,0,1,NÃO
2,40351,40351,40351,40351,INCIDENTE,NaN,NaN,RIO DE JANEIRO,RJ,BRASIL,...,2010-01-03,03:00:00,SIM,FINALIZADA,NaN,NÃO,NaN,0,1,NÃO
3,39527,39527,39527,39527,ACIDENTE,-13.1066666667,-55.9930555556,LUCAS DO RIO VERDE,MT,BRASIL,...,2010-01-04,17:30:00,SIM,FINALIZADA,A-539/CENIPA/2018,SIM,2019-10-28,0,1,NÃO
4,40324,40324,40324,40324,INCIDENTE,NaN,NaN,PELOTAS,RS,BRASIL,...,2010-01-05,19:25:00,SIM,FINALIZADA,NaN,NÃO,NaN,0,1,NÃO

In [26]:
 #apagando dados da linha 0 coluna aerodromo df.loc[0,'ocorrencia_aerodromo']
#todos dados da linha = df.loc[1]=20
#df.loc[:,'total_recomendacoes'] = 10 # alterando todos as linhas de tal coluna

df.loc[0,'ocorrencia_aerodromo'] = ''

In [27]:
df.head(1)

,codigo_ocorrencia1,codigo_ocorrencia2,codigo_ocorrencia3,codigo_ocorrencia4,ocorrencia_classificacao,ocorrencia_latitude,ocorrencia_longitude,ocorrencia_cidade,ocorrencia_uf,ocorrencia_pais,...,ocorrencia_dia,ocorrencia_hora,investigacao_aeronave_liberada,investigacao_status,divulgacao_relatorio_numero,divulgacao_relatorio_publicado,divulgacao_dia_publicacao,total_recomendacoes,total_aeronaves_envolvidas,ocorrencia_saida_pista
0,40211,40211,40211,40211,INCIDENTE,,***,RIO DE JANEIRO,RJ,BRASIL,...,2010-01-03,12:00:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO

In [28]:
#criando o backup de uma coluna
df['ocorrencia_uf_bkp'] = df.ocorrencia_uf
df.head()

,codigo_ocorrencia1,codigo_ocorrencia2,codigo_ocorrencia3,codigo_ocorrencia4,ocorrencia_classificacao,ocorrencia_latitude,ocorrencia_longitude,ocorrencia_cidade,ocorrencia_uf,ocorrencia_pais,...,ocorrencia_hora,investigacao_aeronave_liberada,investigacao_status,divulgacao_relatorio_numero,divulgacao_relatorio_publicado,divulgacao_dia_publicacao,total_recomendacoes,total_aeronaves_envolvidas,ocorrencia_saida_pista,ocorrencia_uf_bkp
0,40211,40211,40211,40211,INCIDENTE,,***,RIO DE JANEIRO,RJ,BRASIL,...,12:00:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO,RJ
1,40349,40349,40349,40349,INCIDENTE,NaN,NaN,BELÉM,PA,BRASIL,...,11:05:00,SIM,FINALIZADA,NaN,NÃO,NaN,0,1,NÃO,PA
2,40351,40351,40351,40351,INCIDENTE,NaN,NaN,RIO DE JANEIRO,RJ,BRASIL,...,03:00:00,SIM,FINALIZADA,NaN,NÃO,NaN,0,1,NÃO,RJ
3,39527,39527,39527,39527,ACIDENTE,-13.1066666667,-55.9930555556,LUCAS DO RIO VERDE,MT,BRASIL,...,17:30:00,SIM,FINALIZADA,A-539/CENIPA/2018,SIM,2019-10-28,0,1,NÃO,MT
4,40324,40324,40324,40324,INCIDENTE,NaN,NaN,PELOTAS,RS,BRASIL,...,19:25:00,SIM,FINALIZADA,NaN,NÃO,NaN,0,1,NÃO,RS

In [30]:
#alterando a coluna ocorrencia pra GRave apenas onde a linha UF = SP
df.loc[df.ocorrencia_uf == 'SP', ['ocorrencia_classificacao']] = 'GRAVE'

In [32]:
#localizando apenas as ocorrencias de SP
df.loc[df.ocorrencia_uf=='SP']

,codigo_ocorrencia1,codigo_ocorrencia2,codigo_ocorrencia3,codigo_ocorrencia4,ocorrencia_classificacao,ocorrencia_latitude,ocorrencia_longitude,ocorrencia_cidade,ocorrencia_uf,ocorrencia_pais,...,ocorrencia_hora,investigacao_aeronave_liberada,investigacao_status,divulgacao_relatorio_numero,divulgacao_relatorio_publicado,divulgacao_dia_publicacao,total_recomendacoes,total_aeronaves_envolvidas,ocorrencia_saida_pista,ocorrencia_uf_bkp
11,40069,40069,40069,40069,GRAVE,-23.5069444444,-46.6341666667,SÃO PAULO,SP,BRASIL,...,14:50:00,SIM,FINALIZADA,A-121/CENIPA/2012,SIM,2012-11-19,8,1,NÃO,SP
16,39809,39809,39809,39809,GRAVE,NaN,NaN,SÃO PAULO,SP,BRASIL,...,15:00:00,***,NaN,NaN,NÃO,NaN,0,1,NÃO,SP
18,39828,39828,39828,39828,GRAVE,***,***,SANTOS,SP,BRASIL,...,17:45:00,***,NaN,NaN,NÃO,NaN,0,1,NÃO,SP
26,39847,39847,39847,39847,GRAVE,NaN,NaN,SOROCABA,SP,BRASIL,...,13:10:00,***,NaN,NaN,NÃO,NaN,0,1,NÃO,SP
27,39768,39768,39768,39768,GRAVE,NaN,NaN,CAMPINAS,SP,BRASIL,...,20:45:00,***,NaN,NaN,NÃO,NaN,0,1,NÃO,SP
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1983,47665,47665,47665,47665,GRAVE,***,***,BOA ESPERANÇA DO SUL,SP,BRASIL,...,20:35:00,***,FINALIZADA,A-071/CENIPA/2013,SIM,2013-07-08,0,1,NÃO,SP
1986,47762,47762,47762,47762,GRAVE,NaN,NaN,BERTIOGA,SP,BRASIL,...,14:10:00,***,FINALIZADA,***,NÃO,NaN,0,1,NÃO,SP
1988,47651,47651,47651,47651,GRAVE,***,***,COSMÓPOLIS,SP,BRASIL,...,20:50:00,***,NaN,NaN,NÃO,NaN,0,1,NÃO,SP
1993,47697,47697,47697,47697,GRAVE,***,***,JUNDIAÍ,SP,BRASIL,...,14:55:00,***,FINALIZADA,IG-075/CENIPA/2013,SIM,2014-04-28,0,1,NÃO,SP
1995,47659,47659,47659,47659,GRAVE,-23.506667°,-46.633889°,CAJAMAR,SP,BRASIL,...,14:00:00,***,ATIVA,A-077/CENIPA/2013,NÃO,NaN,0,1,NÃO,SP

LImpando os dados: procurar os dados que nao foram informados
ocorrencia_uf
**
ocorrencia_aerodromo
###!
####
****
*****
ocorrencia_hora
NULL

In [33]:
df.head()

,codigo_ocorrencia1,codigo_ocorrencia2,codigo_ocorrencia3,codigo_ocorrencia4,ocorrencia_classificacao,ocorrencia_latitude,ocorrencia_longitude,ocorrencia_cidade,ocorrencia_uf,ocorrencia_pais,...,ocorrencia_hora,investigacao_aeronave_liberada,investigacao_status,divulgacao_relatorio_numero,divulgacao_relatorio_publicado,divulgacao_dia_publicacao,total_recomendacoes,total_aeronaves_envolvidas,ocorrencia_saida_pista,ocorrencia_uf_bkp
0,40211,40211,40211,40211,INCIDENTE,,***,RIO DE JANEIRO,RJ,BRASIL,...,12:00:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO,RJ
1,40349,40349,40349,40349,INCIDENTE,NaN,NaN,BELÉM,PA,BRASIL,...,11:05:00,SIM,FINALIZADA,NaN,NÃO,NaN,0,1,NÃO,PA
2,40351,40351,40351,40351,INCIDENTE,NaN,NaN,RIO DE JANEIRO,RJ,BRASIL,...,03:00:00,SIM,FINALIZADA,NaN,NÃO,NaN,0,1,NÃO,RJ
3,39527,39527,39527,39527,ACIDENTE,-13.1066666667,-55.9930555556,LUCAS DO RIO VERDE,MT,BRASIL,...,17:30:00,SIM,FINALIZADA,A-539/CENIPA/2018,SIM,2019-10-28,0,1,NÃO,MT
4,40324,40324,40324,40324,INCIDENTE,NaN,NaN,PELOTAS,RS,BRASIL,...,19:25:00,SIM,FINALIZADA,NaN,NÃO,NaN,0,1,NÃO,RS

In [35]:
df.loc[df.ocorrencia_aerodromo == '****', ['ocorrencia_aerodromo']] = pd.NA

In [36]:
df.head()

,codigo_ocorrencia1,codigo_ocorrencia2,codigo_ocorrencia3,codigo_ocorrencia4,ocorrencia_classificacao,ocorrencia_latitude,ocorrencia_longitude,ocorrencia_cidade,ocorrencia_uf,ocorrencia_pais,...,ocorrencia_hora,investigacao_aeronave_liberada,investigacao_status,divulgacao_relatorio_numero,divulgacao_relatorio_publicado,divulgacao_dia_publicacao,total_recomendacoes,total_aeronaves_envolvidas,ocorrencia_saida_pista,ocorrencia_uf_bkp
0,40211,40211,40211,40211,INCIDENTE,,***,RIO DE JANEIRO,RJ,BRASIL,...,12:00:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO,RJ
1,40349,40349,40349,40349,INCIDENTE,NaN,NaN,BELÉM,PA,BRASIL,...,11:05:00,SIM,FINALIZADA,NaN,NÃO,NaN,0,1,NÃO,PA
2,40351,40351,40351,40351,INCIDENTE,NaN,NaN,RIO DE JANEIRO,RJ,BRASIL,...,03:00:00,SIM,FINALIZADA,NaN,NÃO,NaN,0,1,NÃO,RJ
3,39527,39527,39527,39527,ACIDENTE,-13.1066666667,-55.9930555556,LUCAS DO RIO VERDE,MT,BRASIL,...,17:30:00,SIM,FINALIZADA,A-539/CENIPA/2018,SIM,2019-10-28,0,1,NÃO,MT
4,40324,40324,40324,40324,INCIDENTE,NaN,NaN,PELOTAS,RS,BRASIL,...,19:25:00,SIM,FINALIZADA,NaN,NÃO,NaN,0,1,NÃO,RS

In [39]:
#funcao replace = mundado todos os itens invalidos por pd.NA
df.replace(['###!','****','***','####','*****','NULL'], pd.NA, inplace=True)

In [43]:
df.isna() #mostrar tudo que não tem dado informado 
df.isna().sum() #somando todos na  isna ou isnull

codigo_ocorrencia1                   0
codigo_ocorrencia2                   0
codigo_ocorrencia3                   0
codigo_ocorrencia4                   0
ocorrencia_classificacao             0
ocorrencia_latitude               1406
ocorrencia_longitude              1408
ocorrencia_cidade                    0
ocorrencia_uf                        0
ocorrencia_pais                      0
ocorrencia_aerodromo               928
ocorrencia_dia                       0
ocorrencia_hora                      0
investigacao_aeronave_liberada    1148
investigacao_status                118
divulgacao_relatorio_numero       1254
divulgacao_relatorio_publicado       0
divulgacao_dia_publicacao         1422
total_recomendacoes                  0
total_aeronaves_envolvidas           0
ocorrencia_saida_pista               0
ocorrencia_uf_bkp                    0
dtype: int64

In [46]:
#colocar algum valor todos os dados nao informado
df.fillna(10, inplace=True) # inplace muda o data set sem inplace só em tempo de execução

In [47]:
df.isna().sum()

codigo_ocorrencia1                0
codigo_ocorrencia2                0
codigo_ocorrencia3                0
codigo_ocorrencia4                0
ocorrencia_classificacao          0
ocorrencia_latitude               0
ocorrencia_longitude              0
ocorrencia_cidade                 0
ocorrencia_uf                     0
ocorrencia_pais                   0
ocorrencia_aerodromo              0
ocorrencia_dia                    0
ocorrencia_hora                   0
investigacao_aeronave_liberada    0
investigacao_status               0
divulgacao_relatorio_numero       0
divulgacao_relatorio_publicado    0
divulgacao_dia_publicacao         0
total_recomendacoes               0
total_aeronaves_envolvidas        0
ocorrencia_saida_pista            0
ocorrencia_uf_bkp                 0
dtype: int64

In [48]:
df.head()

,codigo_ocorrencia1,codigo_ocorrencia2,codigo_ocorrencia3,codigo_ocorrencia4,ocorrencia_classificacao,ocorrencia_latitude,ocorrencia_longitude,ocorrencia_cidade,ocorrencia_uf,ocorrencia_pais,...,ocorrencia_hora,investigacao_aeronave_liberada,investigacao_status,divulgacao_relatorio_numero,divulgacao_relatorio_publicado,divulgacao_dia_publicacao,total_recomendacoes,total_aeronaves_envolvidas,ocorrencia_saida_pista,ocorrencia_uf_bkp
0,40211,40211,40211,40211,INCIDENTE,,10,RIO DE JANEIRO,RJ,BRASIL,...,12:00:00,SIM,FINALIZADA,10,NÃO,10,0,1,NÃO,RJ
1,40349,40349,40349,40349,INCIDENTE,10,10,BELÉM,PA,BRASIL,...,11:05:00,SIM,FINALIZADA,10,NÃO,10,0,1,NÃO,PA
2,40351,40351,40351,40351,INCIDENTE,10,10,RIO DE JANEIRO,RJ,BRASIL,...,03:00:00,SIM,FINALIZADA,10,NÃO,10,0,1,NÃO,RJ
3,39527,39527,39527,39527,ACIDENTE,-13.1066666667,-55.9930555556,LUCAS DO RIO VERDE,MT,BRASIL,...,17:30:00,SIM,FINALIZADA,A-539/CENIPA/2018,SIM,2019-10-28,0,1,NÃO,MT
4,40324,40324,40324,40324,INCIDENTE,10,10,PELOTAS,RS,BRASIL,...,19:25:00,SIM,FINALIZADA,10,NÃO,10,0,1,NÃO,RS

In [49]:
df.replace([10], pd.NA, inplace=True)

In [50]:
df.isna().sum()

codigo_ocorrencia1                   0
codigo_ocorrencia2                   0
codigo_ocorrencia3                   0
codigo_ocorrencia4                   0
ocorrencia_classificacao             0
ocorrencia_latitude               1406
ocorrencia_longitude              1408
ocorrencia_cidade                    0
ocorrencia_uf                        0
ocorrencia_pais                      0
ocorrencia_aerodromo               928
ocorrencia_dia                       0
ocorrencia_hora                      0
investigacao_aeronave_liberada    1148
investigacao_status                118
divulgacao_relatorio_numero       1254
divulgacao_relatorio_publicado       0
divulgacao_dia_publicacao         1422
total_recomendacoes                  2
total_aeronaves_envolvidas           0
ocorrencia_saida_pista               0
ocorrencia_uf_bkp                    0
dtype: int64

In [53]:
#alterar somente em alguns lugares que tem NA
df.fillna(value={'total_recomendacoes':10}, inplace=True)

In [54]:
df.isna().sum()

codigo_ocorrencia1                   0
codigo_ocorrencia2                   0
codigo_ocorrencia3                   0
codigo_ocorrencia4                   0
ocorrencia_classificacao             0
ocorrencia_latitude               1406
ocorrencia_longitude              1408
ocorrencia_cidade                    0
ocorrencia_uf                        0
ocorrencia_pais                      0
ocorrencia_aerodromo               928
ocorrencia_dia                       0
ocorrencia_hora                      0
investigacao_aeronave_liberada    1148
investigacao_status                118
divulgacao_relatorio_numero       1254
divulgacao_relatorio_publicado       0
divulgacao_dia_publicacao         1422
total_recomendacoes                  0
total_aeronaves_envolvidas           0
ocorrencia_saida_pista               0
ocorrencia_uf_bkp                    0
dtype: int64

In [55]:
#excluindo coluna
df.drop(['ocorrencia_uf_bkp'], axis=1, inplace=True) #muda o eixo 0 linha 1 coluna

In [56]:
df.head(10)

,codigo_ocorrencia1,codigo_ocorrencia2,codigo_ocorrencia3,codigo_ocorrencia4,ocorrencia_classificacao,ocorrencia_latitude,ocorrencia_longitude,ocorrencia_cidade,ocorrencia_uf,ocorrencia_pais,...,ocorrencia_dia,ocorrencia_hora,investigacao_aeronave_liberada,investigacao_status,divulgacao_relatorio_numero,divulgacao_relatorio_publicado,divulgacao_dia_publicacao,total_recomendacoes,total_aeronaves_envolvidas,ocorrencia_saida_pista
0,40211,40211,40211,40211,INCIDENTE,,<NA>,RIO DE JANEIRO,RJ,BRASIL,...,2010-01-03,12:00:00,SIM,FINALIZADA,<NA>,NÃO,<NA>,0,1,NÃO
1,40349,40349,40349,40349,INCIDENTE,<NA>,<NA>,BELÉM,PA,BRASIL,...,2010-01-03,11:05:00,SIM,FINALIZADA,<NA>,NÃO,<NA>,0,1,NÃO
2,40351,40351,40351,40351,INCIDENTE,<NA>,<NA>,RIO DE JANEIRO,RJ,BRASIL,...,2010-01-03,03:00:00,SIM,FINALIZADA,<NA>,NÃO,<NA>,0,1,NÃO
3,39527,39527,39527,39527,ACIDENTE,-13.1066666667,-55.9930555556,LUCAS DO RIO VERDE,MT,BRASIL,...,2010-01-04,17:30:00,SIM,FINALIZADA,A-539/CENIPA/2018,SIM,2019-10-28,0,1,NÃO
4,40324,40324,40324,40324,INCIDENTE,<NA>,<NA>,PELOTAS,RS,BRASIL,...,2010-01-05,19:25:00,SIM,FINALIZADA,<NA>,NÃO,<NA>,0,1,NÃO
5,39807,39807,39807,39807,INCIDENTE,<NA>,<NA>,SALVADOR,BA,BRASIL,...,2010-01-06,17:53:00,<NA>,<NA>,<NA>,NÃO,<NA>,0,1,NÃO
6,40215,40215,40215,40215,INCIDENTE,<NA>,<NA>,COARI,AM,BRASIL,...,2010-01-07,18:40:00,SIM,FINALIZADA,<NA>,NÃO,<NA>,0,1,SIM
7,39707,39707,39707,39707,INCIDENTE GRAVE,-6.5319444444,-64.3805555556,CANUTAMA,AM,BRASIL,...,2010-01-09,12:30:00,SIM,FINALIZADA,IG-028/CENIPA/2011,SIM,2011-07-21,3,1,NÃO
8,39156,39156,39156,39156,INCIDENTE GRAVE,-15.2402777778,-59.3541666667,CASCAVEL,PR,BRASIL,...,2010-01-10,23:15:00,SIM,FINALIZADA,I-004/CENIPA/2011,SIM,2011-06-30,2,1,NÃO
9,39711,39711,39711,39711,INCIDENTE GRAVE,<NA>,<NA>,PARÁ DE MINAS,MG,BRASIL,...,2010-01-10,20:00:00,<NA>,<NA>,<NA>,NÃO,<NA>,0,1,NÃO

In [58]:
#excluindo valores nao informados
#df.dropna() ##exclui tambem as linhas
df.dropna(subset=['ocorrencia_latitude'])#informar por qual coluna que procurar o NA

,codigo_ocorrencia1,codigo_ocorrencia2,codigo_ocorrencia3,codigo_ocorrencia4,ocorrencia_classificacao,ocorrencia_latitude,ocorrencia_longitude,ocorrencia_cidade,ocorrencia_uf,ocorrencia_pais,...,ocorrencia_dia,ocorrencia_hora,investigacao_aeronave_liberada,investigacao_status,divulgacao_relatorio_numero,divulgacao_relatorio_publicado,divulgacao_dia_publicacao,total_recomendacoes,total_aeronaves_envolvidas,ocorrencia_saida_pista
0,40211,40211,40211,40211,INCIDENTE,,<NA>,RIO DE JANEIRO,RJ,BRASIL,...,2010-01-03,12:00:00,SIM,FINALIZADA,<NA>,NÃO,<NA>,0,1,NÃO
3,39527,39527,39527,39527,ACIDENTE,-13.1066666667,-55.9930555556,LUCAS DO RIO VERDE,MT,BRASIL,...,2010-01-04,17:30:00,SIM,FINALIZADA,A-539/CENIPA/2018,SIM,2019-10-28,0,1,NÃO
7,39707,39707,39707,39707,INCIDENTE GRAVE,-6.5319444444,-64.3805555556,CANUTAMA,AM,BRASIL,...,2010-01-09,12:30:00,SIM,FINALIZADA,IG-028/CENIPA/2011,SIM,2011-07-21,3,1,NÃO
8,39156,39156,39156,39156,INCIDENTE GRAVE,-15.2402777778,-59.3541666667,CASCAVEL,PR,BRASIL,...,2010-01-10,23:15:00,SIM,FINALIZADA,I-004/CENIPA/2011,SIM,2011-06-30,2,1,NÃO
11,40069,40069,40069,40069,GRAVE,-23.5069444444,-46.6341666667,SÃO PAULO,SP,BRASIL,...,2010-01-10,14:50:00,SIM,FINALIZADA,A-121/CENIPA/2012,SIM,2012-11-19,8,1,NÃO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1989,47694,47694,47694,47694,ACIDENTE,-15.0583333333,-57.1825,BARRA DO BUGRES,MT,BRASIL,...,2013-04-19,19:30:00,<NA>,FINALIZADA,A-072/CENIPA/2013,SIM,2013-09-16,0,1,SIM
1994,47876,47876,47876,47876,ACIDENTE,-11.885,-55.5861111111,SINOP,MT,BRASIL,...,2013-04-21,12:50:00,<NA>,FINALIZADA,A-074/CENIPA/2013,SIM,2016-03-18,1,1,NÃO
1995,47659,47659,47659,47659,GRAVE,-23.506667°,-46.633889°,CAJAMAR,SP,BRASIL,...,2013-04-22,14:00:00,<NA>,ATIVA,A-077/CENIPA/2013,NÃO,<NA>,0,1,NÃO
1996,47661,47661,47661,47661,ACIDENTE,-6.6294444444,-72.7055555556,ATALAIA DO NORTE,AM,BRASIL,...,2013-04-22,19:00:00,SIM,FINALIZADA,A-035/CENIPA/2013,SIM,2013-08-14,2,1,NÃO
1997,47699,47699,47699,47699,INCIDENTE GRAVE,-1.3847222222,-48.4788888889,BELÉM,PA,BRASIL,...,2013-04-22,11:28:00,<NA>,FINALIZADA,IG-076/CENIPA/2013,SIM,2013-09-16,2,1,SIM

In [ ]:
#tirando valores duplicados
df.drop_duplicates(inplace=True)